export default {
  MESSAGE_SUCCESS: 'MESSAGE_SUCCESS',
  REQUEST_EXAMPLE: 'REQUEST_EXAMPLE',
  RECIEVE_EXAMPLE: 'RECIEVE_EXAMPLE',
  FAILURE_EXAMPLE: 'FAILURE_EXAMPLE',
  ADMIN_CHANGE_TABLE: 'ADMIN_CHANGE_TABLE',
  ADMIN_CHANGE_ADMIN: 'ADMIN_CHANGE_ADMIN',
}
