export default {
  MESSAGE_SUCCESS: 'MESSAGE_SUCCESS',
  REQUEST_EXAMPLE: 'REQUEST_EXAMPLE',
  RECIEVE_EXAMPLE: 'RECIEVE_EXAMPLE',
  FAILURE_EXAMPLE: 'FAILURE_EXAMPLE',
  UPDATE_FIRST_NAME: 'UPDATE_FIRST_NAME'
}
